import { useState, useRef } from 'react';

export default function AddScreenshotModal({ categories, onAdd, onClose }) {
  const [files, setFiles] = useState([]), [previews, setPreviews] = useState([]), [category, setCategory] = useState('Personal'), [customCategory, setCustomCategory] = useState(''), [creatingCategory, setCreatingCategory] = useState(false), [note, setNote] = useState(''), [dragging, setDragging] = useState(false), [adding, setAdding] = useState(false);
  const inputRef = useRef();
  const setSelectedFiles = (selected) => { const images = Array.from(selected).filter((file) => file.type.startsWith('image/')); setFiles(images); setPreviews(images.map((file) => URL.createObjectURL(file))); };
  const submit = async (event) => { event.preventDefault(); if (!files.length) return; setAdding(true); await onAdd(files, creatingCategory && customCategory.trim() ? customCategory.trim() : category, note); setAdding(false); };
  const remove = (index) => { setFiles((current) => current.filter((_, i) => i !== index)); setPreviews((current) => current.filter((_, i) => i !== index)); };
  return <div className="modal-overlay" onClick={onClose} role="dialog" aria-modal="true" aria-label="Import screenshots"><section className="modal" onClick={(event) => event.stopPropagation()}><header className="modal__header"><h2 className="modal__title">Import screenshots</h2><button className="modal__close" onClick={onClose} aria-label="Close">×</button></header><form className="modal__body" onSubmit={submit}>
    <div className={`dropzone ${dragging ? 'dropzone--active' : ''}`} onDragOver={(event) => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={(event) => { event.preventDefault(); setDragging(false); setSelectedFiles(event.dataTransfer.files); }} onClick={() => inputRef.current.click()} role="button" tabIndex={0} onKeyDown={(event) => event.key === 'Enter' && inputRef.current.click()}><span className="dropzone__icon">+</span><p className="dropzone__text">{files.length ? `${files.length} capture${files.length === 1 ? '' : 's'} selected` : 'Choose screenshots to import'}</p><p className="dropzone__hint">Drop images here or browse your device</p><input ref={inputRef} type="file" accept="image/*" multiple hidden onChange={(event) => setSelectedFiles(event.target.files)} /></div>
    {previews.length > 0 && <div className="modal__previews">{previews.map((url, index) => <div className="modal__preview-wrap" key={url}><img className="modal__preview-img" src={url} alt={files[index]?.name} width="88" height="60" /><button type="button" className="modal__preview-remove" onClick={() => remove(index)} aria-label={`Remove ${files[index]?.name}`}>×</button><p className="modal__preview-name">{files[index]?.name}</p></div>)}</div>}
    <div className="modal__field"><label className="field-label">Category</label><select className="field-select" value={creatingCategory ? '__new__' : category} onChange={(event) => { if (event.target.value === '__new__') setCreatingCategory(true); else { setCreatingCategory(false); setCategory(event.target.value); } }}>{categories.map((item) => <option key={item} value={item}>{item}</option>)}<option value="__new__">New category…</option></select>{creatingCategory && <input className="field-input" placeholder="Name your category" value={customCategory} onChange={(event) => setCustomCategory(event.target.value)} />}</div>
    <div className="modal__field"><label className="field-label">Note <em>(optional)</em></label><textarea className="field-textarea" rows={2} placeholder="Add a note for these captures" value={note} onChange={(event) => setNote(event.target.value)} /></div><footer className="modal__footer"><button type="button" className="btn btn--ghost" onClick={onClose}>Cancel</button><button type="submit" className="btn btn--primary" disabled={!files.length || adding}>{adding ? 'Importing…' : `Import ${files.length || ''}`}</button></footer>
  </form></section></div>;
}
